node_js:
  - '9'
language: node_js
services:
  - docker
addons:
    apt:
        packages:
            - sshpass
cache:
  directories:
    - node_modules
before_script:
  - cd api
script:
  - npm install